# Generated by Django 3.0.8 on 2020-07-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200717_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.FloatField()),
                ('fk_exp_id', models.IntegerField()),
                ('battery_level', models.IntegerField()),
            ],
        ),
    ]
