# Generated by Django 3.0.8 on 2020-07-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_uploaddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('tcn', models.CharField(max_length=50)),
                ('src_uid', models.CharField(max_length=50)),
                ('ble_strength', models.FloatField()),
                ('exp_id', models.IntegerField()),
                ('current_user_motion_status', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='expire_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
