# Generated by Django 3.0.8 on 2020-07-18 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_tcn_rx_tcn_tx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tcn_tx',
            old_name='own_tch',
            new_name='own_tcn',
        ),
    ]
