# Generated by Django 3.0.8 on 2020-07-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_exp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
