# Generated by Django 3.0.8 on 2020-07-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='exp_id',
            field=models.IntegerField(null=True),
        ),
    ]
