# Generated by Django 3.0.8 on 2020-07-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_last_api_calling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcn_rx',
            name='rx_muuid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tcn_rx',
            name='rx_tcn',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tcn_rx',
            name='tcn',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tcn_rx',
            name='tx_muuid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tcn_tx',
            name='own_tcn',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tcn_tx',
            name='tx_muuid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tcn_tx',
            name='tx_tcn',
            field=models.CharField(max_length=100),
        ),
    ]
