# Generated by Django 3.0.8 on 2020-07-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200719_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcn',
            name='src_uid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tcn',
            name='tcn',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tcn',
            name='uid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
