# Generated by Django 3.0.8 on 2020-07-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_attacklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_id', models.CharField(max_length=2, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='exp_id',
        ),
    ]
