# Generated by Django 3.0.8 on 2020-07-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200720_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcn_rx',
            name='exp_id',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tcn_tx',
            name='exp_id',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
