# Generated by Django 3.0.8 on 2020-07-20 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200720_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tcn_rx',
            old_name='uxix_timestamp',
            new_name='unix_timestamp',
        ),
        migrations.RenameField(
            model_name='tcn_tx',
            old_name='uxix_timestamp',
            new_name='unix_timestamp',
        ),
    ]
