# Generated by Django 3.0.8 on 2020-07-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_tcn_tx_tx_muuid_short'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attacklog',
            old_name='log',
            new_name='blind_log',
        ),
        migrations.AddField(
            model_name='attacklog',
            name='unix_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
