# Generated by Django 3.0.8 on 2020-07-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20200721_1117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TCN',
        ),
        migrations.DeleteModel(
            name='UploadData',
        ),
    ]
