# Generated by Django 3.0.8 on 2020-07-27 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20200727_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcn_rx',
            name='rx_muuid',
        ),
    ]
